[build]
command = "npm run build"
publish = "build"

[build.environment]
REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
